### PR TITLE
[ENHANCEMENT] #63 - Implement real time synchronisation 

### PR DESCRIPTION
**Pull request by JensGryspeert**
**Describe Pull request**
This pull request includes several commits that aim to enhance the time synchronization and network clock time updating functionality in the project which there is now an option to activate real time synchronization.

**_The specific changes made are as follows:_**

1. Refactor time synchronization and network clock time updating
   - Determined the time increment based on the RealTimeSync configuration setting.
   - Used the GetLocalTime() function to retrieve the local time in RealTimeSync mode.

2. Implement real-time synchronization server-side
   - Implemented real-time synchronization functionality on the server-side.
   - Ensured that the server time is set based on the actual real-time retrieved from an API.

3. Implement function to fetch current Unix time from API
   - Added a function to retrieve the current Unix time from an API.
   - Used the function to set the server time in the real-time synchronization process.

4. Add variable in config to activate real-time sync
   - Added a configuration variable to enable/disable real-time synchronization.

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all its functionality? [**yes**/no] (Be honest)
- Does your code fit the style guidelines? [**yes**/no]
- Does your PR fit the contribution guidelines? [**yes**/no]

### CODE REVIEW

**Review by jayyy299 — APPROVED** [review]

**Comment by JensGryspeert** [comment]
Can someone review this? Just retrieved an message in mail the following:
```
This PR has had 60 days of inactivity & will close within 7 days

```

**Review by citRaTTV — APPROVED** [review]

**Comment by GhzGarage** [comment]
@JensGryspeert Could you fix the conflict if possible please

**Comment by JensGryspeert** [comment]
I will, hope the PR will be merged then. Otherwise the conflict didn't appeared :). I'll do this this evening.

**Comment by citRaTTV** [comment]
> I will, hope the PR will be merged then. Otherwise the conflict didn't appeared :). I'll do this this evening.

@JensGryspeert still seeing this conflict. Have you had a chance to sync your branch with latest & resolve it?

**Comment by JensGryspeert** [comment]
Not yet. Forgot it to be honest. Will do this tomorrow. I've planned it in my calendar.

**Comment by JensGryspeert** [comment]
> > I will, hope the PR will be merged then. Otherwise the conflict didn't appeared :). I'll do this this evening.
> 
> @JensGryspeert still seeing this conflict. Have you had a chance to sync your branch with latest & resolve it?

Rebased the branch and resolved it ;)

**Review by citRaTTV — APPROVED** [review]

**Pull request merged**
