### PR TITLE
Reworking time sync

### PR DESCRIPTION
**Pull request by CodeRedDev**
This reworks the time sync so that time is synced with the real (ooc) time and with meaningful time calculations (see #51).

It also adds the command `resettime` to reset the time to real time after `time` was used.

Plus the commands are now handled over `QBCore.Commands`

### CODE REVIEW

**Comment by CodeRedDev** [comment]
We're discussing some issue in this [guilded post](https://www.guilded.gg/qbcore/groups/EdxA1Wez/channels/b742d285-32d4-452e-ac24-6ee3a119a789/forums/1114239064)

**Comment by nullvariable** [comment]
Hi @CodeRedDev thanks for your work here! I'm having trouble fully digesting all of the changes here. Would it be possible to split these up into distinct PRs, one for the command changes, and one for the time calculations?

**Comment by CodeRedDev** [comment]
@nullvariable Sure. The time calculations have some problems though. As the time in GTA obviously goes faster than real time there are a lot of perceptible jumps. Unfortunately I do not know if this can be optimized by doing server time pushes more often or the like.

**Comment by CodeRedDev** [comment]
QBCore Commands migration is now in PR #56

**Review by Re1ease — COMMENTED** [review]
At a glance, the time sync rework looks fine.

However, upon testing the reworked time sync, I noticed that sometimes it has a rather long delay (up to 20 seconds) when changing time manually. Do you get the same issue if you attempt to reproduce the test?

I can't pinpoint what's causing the issue from your code, and a fresh fork from the script doesn't cause that delay.

**Comment by Wafflzdev** [comment]
Hello,

Is this still being worked on or need to be closed?

**Comment by CodeRedDev** [comment]
Currently I'm not working on any scripting so this might be closed.

**Pull request closed without merging**
