### PR TITLE
[ENHANCEMENT] Add getTime export

### PR DESCRIPTION
**Pull request by meta-hub**
**Describe Pull request**
Adds getTime export for server-side.

**Questions:**
Q: Have you personally loaded this code into an updated qbcore project and checked all it's functionality?
A: Yes

Q: Does your code fit the style guidelines?
A: Yes

Q: Does your PR fit the contribution guidelines?
A: Yes

### CODE REVIEW

**Comment by Z3rio** [comment]
What is this trying to return?
Because from what I see, it doesnt return in game time nor IRL time.

**Review by meta-hub — COMMENTED** [review]
This is a breaking change for the resource I use this for already.

**Comment by meta-hub** [comment]
> What is this trying to return? Because from what I see, it doesnt return in game time nor IRL time.

It returns the game time. Example:

```lua
local WeatherSync = exports["qb-weathersync"]

RegisterCommand("testtime", function(source, args)
    local setHour = tonumber(args[1] or 12)
    local setMinute = tonumber(args[2] or 0)

    WeatherSync:setTime(setHour, setMinute)

    local retHour,retMinute = WeatherSync:getTime()

    print("set", setHour, setMinute)
    print("ret", retHour, retMinute)
end, false)
```

Can I ask you to revert your commit

**Review by Z3rio — APPROVED** [review]
LGTM

**Pull request merged**
