### PR TITLE
Merge qb-event

### PR DESCRIPTION
**Pull request by evanillaa**

### CODE REVIEW

**Comment by zfbx** [comment]
What is this? I don't know if this should be merged, seems like it's be better as it's own resource

**Comment by evanillaa** [comment]
This is an existing resource for the project
But he forgot to add it to the project
standalone script
But it works synchronously with the weather script
I think it's good

**Comment by zfbx** [comment]
It uses triggerEvents and exports so it should can work outside of it, it's a bit heavy, the example video is 20mb that loads every time you load in to the game with this included. This would be much better included in some hacker resource I think, however the thunder and time change stuff is a bit OP for a hacker xD. I'd throw this all into a public [gist](https://gist.github.com/) and add it to the readme as a suggestion since it requires actual effort to configure it to fit your city and have a purpose for it. I personally don't see how you'd use it in a RP scenario as it would be so jarring and break immersion

**Comment by evanillaa** [comment]
Yes you are right
I will close the PR

**Pull request closed without merging**
